logging.config: classpath:config/logback.xml.xml
logging.level.io.netty.handler.logging.LoggingHandler: INFO

---

logging.file: http-proxy-netty.log
logging.level.io.netty.handler.logging.LoggingHandler: ERROR
